//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ApartmentId { get; set; }
        public int BuildingId { get; set; }
        public string Type { get; set; }
        public int StatusId { get; set; }
        public decimal Price { get; set; }
        public int UserId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
    }
}
